### ISSUE TITLE
unable to run r200 with ROS

### ISSUE THREAD

**Issue by ahmohamed1** [jetsonhacks/installRealSenseCameraROS#1]
Hi,

I am working with Jetson tx1 and realSense R200. The r200 work fine when I run the example with sudo, However, when I start use it with ros using roslaunch realsense_camera r200_nodelet_disable_color.test  I have this error 

`[ERROR] [1473416123.486250931]: /camera - Error calling rs_create_context ( api_version:4 ): 
UVCIOC_CTRL_QUERY:UVC_SET_CUR error 2, No such file or directory`

which is similar to the error I have it when I run the example without sudo. I am using JetBack 2.2.1 32bit. 

Thank you

**Comment by jetsonhacks** [comment]
It sounds like your udev permissions are not set properly. This should have been set properly when installing librealsense. See: http://jetsonhacks.com/2016/06/23/realsense-camera-ros-install-jetson-tk1/ for a recap, and check out the installLibrealsense scripts to make sure that the udev was set correctly on your TK1.

**Comment by ahmohamed1** [comment]
I did re-install it again following the steps you explained in the link but still I have the same issue. 

but still I have an issue with the udev. to run the example came with librealsense I have to run them as root. I remove and add again the rules in /etc/udev/rule.d/  and nothing change I have to run the example  as root to work.

Thank you for replaying.

**Comment by jetsonhacks** [comment]
Are you using a Jetson TK1 or TX1?

You can try:
$ sudo usermod -a -G video $USER
to see if that helps

**Comment by ahmohamed1** [comment]
I am using Jetson TX1 with Jetback 2.2.1 32Bit.

Already, I have used this code but's it's not use. 
I re-flash my Jetson twice but still I have to run the example as root to run the camera.

**Comment by jetsonhacks** [comment]
These scripts are for installing the RealSense R200 on the Jetson TK1. The TX1 uses a different machine architecture, which requires a different installation method of librealsense.
